import datetime
from sqlalchemy.orm import Session

from ..models.analysis_record import AnalysisRecord
from ..settings import settings


def save_analysis(
    db: Session,
    ticker: str,
    analysis_text: str,
    structured_output: str,
    signal: str,
    confidence: int,
    risk_level: str,
) -> AnalysisRecord:
    """Persist a narrative analysis together with Gemini's structured JSON output and key metadata.

    Args:
        db: SQLAlchemy Session instance.
        ticker: Stock ticker symbol.
        analysis_text: Full natural‑language analysis generated by Gemini.
        structured_output: The raw JSON string (validated) returned by Gemini.
        signal: BUY/SELL/HOLD extracted from the JSON.
        confidence: Confidence score (0‑100) extracted from the JSON.
        risk_level: Risk level extracted from the JSON.
    Returns:
        The created ``AnalysisRecord`` instance (with ``id`` populated).
    """
    record = AnalysisRecord(
        ticker=ticker,
        analysis_text=analysis_text,
        structured_output=structured_output,
        signal=signal,
        confidence=confidence,
        risk_level=risk_level,
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return record


def get_latest_analysis(db: Session, ticker: str) -> AnalysisRecord | None:
    """Return the most recent analysis for a ticker, or ``None`` if none exist."""
    return (
        db.query(AnalysisRecord)
        .filter(AnalysisRecord.ticker == ticker)
        .order_by(AnalysisRecord.created_at.desc())
        .first()
    )


def purge_old_records(db: Session) -> None:
    """Delete analysis records older than the configured retention period.

    The retention period is defined by ``settings.ANALYSIS_RETENTION_DAYS``.
    """
    cutoff = datetime.datetime.utcnow() - datetime.timedelta(days=settings.ANALYSIS_RETENTION_DAYS)
    db.query(AnalysisRecord).filter(AnalysisRecord.created_at < cutoff).delete(synchronize_session=False)
    db.commit()


def get_recent_analyses(db: Session, ticker: str, limit: int = 5) -> list[AnalysisRecord]:
    """Return the most recent *limit* analyses for a ticker."""
    return (
        db.query(AnalysisRecord)
        .filter(AnalysisRecord.ticker == ticker)
        .order_by(AnalysisRecord.created_at.desc())
        .limit(limit)
        .all()
    )

def get_analyses_by_signal(db: Session, ticker: str, signal: str) -> list[AnalysisRecord]:
    """Return all analyses for *ticker* that have the given *signal* (BUY/SELL/HOLD)."""
    return (
        db.query(AnalysisRecord)
        .filter(AnalysisRecord.ticker == ticker, AnalysisRecord.signal == signal)
        .order_by(AnalysisRecord.created_at.desc())
        .all()
    )

def get_analyses_by_date_range(db: Session, ticker: str, start: datetime.datetime, end: datetime.datetime) -> list[AnalysisRecord]:
    """Return analyses for *ticker* whose created_at is between *start* and *end* (inclusive)."""
    return (
        db.query(AnalysisRecord)
        .filter(
            AnalysisRecord.ticker == ticker,
            AnalysisRecord.created_at >= start,
            AnalysisRecord.created_at <= end,
        )
        .order_by(AnalysisRecord.created_at.desc())
        .all()
    )
