from pydantic import BaseModel, Field, conint
from typing import List, Dict, Any, Literal, Optional

class OpportunityResponse(BaseModel):
    ticker: str = Field(..., description="The stock ticker symbol")
    confidence: conint(ge=0, le=100) = Field(..., description="Confidence score 0-100")
    risk_level: Literal["Low", "Medium", "High", "Unknown"] = Field(..., description="Risk assessment")
    opportunity: str = Field(..., description="What opportunity exists?")
    why_interesting: str = Field(..., description="Why is it interesting?")
    catalyst: str = Field(..., description="What is the catalyst?")
    investor_appeal: str = Field(..., description="Why should an investor care?")
    risks: str = Field(..., description="What are the risks?")
    # Patch Detailing v1 fields
    summary: str = Field(..., description="Executive summary")
    company_overview: str = Field(..., description="Company overview and market context")
    current_market_structure: str = Field(..., description="Current market structure description")
    chart_analysis: str = Field(..., description="Detailed chart analysis")
    volume_analysis: str = Field(..., description="Volume behavior analysis")
    current_price_position: str = Field(..., description="Current price position relative to range")
    trend_structure: str = Field(..., description="Trend and structure narrative")
    support_resistance_analysis: str = Field(..., description="Support/Resistance analysis")
    volume_profile_analysis: str = Field(..., description="Volume profile insights")
    technical_story: str = Field(..., description="Technical story narrative")
    investment_narrative: str = Field(..., description="Overall investment narrative")
    bull_thesis: str = Field(..., description="Bull thesis narrative")
    bear_thesis: str = Field(..., description="Bear thesis narrative")
    opportunity_thesis: str = Field(..., description="Overall opportunity thesis")
    risk_analysis: str = Field(..., description="Risk analysis narrative")
    catalysts: List[str] = Field(..., description="List of catalysts")
    institutional_activity: str = Field(..., description="Institutional activity narrative")
    trend_analysis: str = Field(..., description="Trend analysis narrative")
    momentum_analysis: str = Field(..., description="Momentum analysis narrative")
    market_sentiment: str = Field(..., description="Market sentiment narrative")
    warnings: List[str] = Field(..., description="Risk warnings or caveats")
    key_levels: List[str] = Field(..., description="Important support/resistance levels")
    # Trade setup fields
    entry_strategy: str = Field(..., description="Entry strategy narrative")
    exit_strategy: str = Field(..., description="Exit strategy narrative")
    holding_period: str = Field(..., description="Suggested holding period")
    entry_zone: Dict[str, float] = Field(..., description="Entry price range with keys 'min' and 'max'")
    stop_loss: float = Field(..., description="Stop‑loss price")
    take_profit: Dict[str, float] = Field(..., description="Take‑profit targets with keys 'tp1' and 'tp2'")
    risk_reward_ratio: float = Field(..., description="Risk/Reward ratio")
    # Quantitative assessment
    alignment_score: float = Field(..., description="Overall alignment score (0‑100)")
    # Patch Detailing v2 fields
    bull_case_probability: conint(ge=0, le=100) = Field(..., description="Probability of bull case (0‑100)")
    base_case_probability: conint(ge=0, le=100) = Field(..., description="Probability of base case (0‑100)")
    bear_case_probability: conint(ge=0, le=100) = Field(..., description="Probability of bear case (0‑100)")
