from pydantic import Field

from .opportunity_response import OpportunityResponse


class RankedOpportunityResponse(OpportunityResponse):
    """Opportunity response enriched with ranking metadata generated by RankingAgent."""

    rank: int = Field(..., description="Position in the ranked list (1 = top)")
    ranking_explanation: str = Field(..., description="Explanation for this specific rank")
    why_ranked_here: str = Field(..., description="Reason why the opportunity received this rank")
